### ISSUE TITLE
[PE-D][Tester E] Message for viewleave command when there are no employees has a minor typo

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-2/tp#163]
The message should rephrase "no employee" to "no employees". Minor grammatical issue.

![image.png](https://raw.githubusercontent.com/wui-hong/ped/main/files/25dab5c4-c274-4310-b777-74ba91b17a55.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: wui-hong/ped#6

**Comment by Leb14** [comment]
Edited the error message
