### ISSUE TITLE
[PE-D][Tester B] Able to input Invalid input for date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W12-2/tp#172]
The current version allows users to add invalid dates like 29/02/2023. (There are only 28 days in February in 2023)

This can lead to errors when users input similar invalid dates.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: InfiBeyond/ped#4

**Comment by jibtaf** [comment]
just do it

**Comment by WeeMingQing** [comment]
Fixed the issue of invalid date being passed in.
