### ISSUE TITLE
[PE-D][Tester E] Minor grammer issue under deleteleave in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-2/tp#173]
A more appropriate rewording of the sentence would be "...by the `INDEX`. Either a single day or leave of multiple days of leave can be deleted."

![image.png](https://raw.githubusercontent.com/wui-hong/ped/main/files/131a82c7-4b0a-424b-a04e-2730f10cecee.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: wui-hong/ped#8

**Comment by jibtaf** [comment]
fix ug
