### ISSUE TITLE
[PE-D][Tester B] Can deduct salary to negative number

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2103T-W12-2/tp#195]
The user is currently able to deduct salary to a negative number. This might require a warning to present errors.

![Screen Shot 2023-11-03 at 6.04.24 PM.png](https://raw.githubusercontent.com/InfiBeyond/ped/main/files/53bb1e8f-731c-47e5-906f-1b6fff610199.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: InfiBeyond/ped#13

**Comment by jibtaf** [comment]
Already mentioned in ug that the value must be positive.
