### ISSUE TITLE
Fix the test cases which are not passing

### ISSUE THREAD

**Issue by Kevin-Liusx** [AY2324S1-CS2103T-W12-2/tp#61]

**Comment by jibtaf** [comment]
Left with these:
<img width="820" alt="Screenshot 2023-10-18 at 16 17 51" src="https://github.com/AY2324S1-CS2103T-W12-2/tp/assets/122149501/3468533f-ad1f-4304-b6bd-42672e542e65">

**Comment by jibtaf** [comment]
Now left with these two under `DleteCommandTest.java`:
<img width="626" alt="Screenshot 2023-10-18 at 16 25 06" src="https://github.com/AY2324S1-CS2103T-W12-2/tp/assets/122149501/9f086cca-e990-49b7-8232-40dc08865a73">
